Fix: return 404 for not existing assets
DE-IBH/b3lb pull request #50
Opened 2021-07-27 14:10 UTC by PhilippKilian

2021-07-27 21:34 UTC, liske requested changes

2021-07-27 21:34 UTC, liske commented on b3lb/rest/views.py
> +    if asset.custom_css:
Should it be `logo`?

2021-07-27 21:34 UTC, liske commented on b3lb/rest/views.py
> +    if asset.custom_css:
Should it be `slide`?

2021-07-28 07:39 UTC, PhilippKilian commented on b3lb/rest/views.py
> +    if asset.custom_css:
yes... fixed

2021-07-28 07:39 UTC, PhilippKilian commented on b3lb/rest/views.py
> +    if asset.custom_css:
yes, fixed

2021-07-28 08:28 UTC, liske approved these changes

2021-07-28 08:37 UTC, merged